version: 2
jobs:
  build:
    machine: true
    #docker:
    #    - image: ncino/ci-sfdx  
    steps:
      - checkout
      - run:
         name: Download DX
         command: wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJf -
      - run:
         name: Install DX
         command: ./sfdx/install
      - run: 
          name: Update DX if necessary
          command: |
            sfdx version
            sfdx plugins --core   
      - run:
          name: create tmp dir and server key; check server key
          command: mkdir tmp; echo $SSL_SERVER_KEY_HEX | xxd -r -ps >> ./tmp/server.key; openssl rsa -in ./tmp/server.key -check -noout
      - run:
          name: auth sfdx
          command: sfdx force:auth:jwt:grant --clientid $DX_CONSUMER_KEY --jwtkeyfile ./tmp/server.key --username sz@appero.com --setdefaultdevhubusername --setalias hub
      - run: 
          name: create scratch org, push source
          command: |
            sfdx force:org:create -s -f config/project-scratch-def.json -a circle_build_$CIRCLE_BUILD_NUM
            sfdx force:source:push -u circle_build_$CIRCLE_BUILD_NUM
      - run: 
          name: run apex tests
          command: |
            mkdir -p ~/apex
            sfdx force:apex:test:run -c -d ~/apex/ -r junit --wait 2 # why does -1 not work here?
      - store_test_results:
          path: ~/apex
      - store_artifacts:
          path: ~/apex   
      - run: 
          name: delete scratch org
          command: sfdx force:org:delete -u circle_build_$CIRCLE_BUILD_NUM -p
          when: always
  