version: 2
jobs:
    setup-dx-environment:
        machine: true 
        steps:
        - run:
            name: Download DX and store 
            command: |
                mkdir ~/tools
                wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJf - --directory ~/tools/
                ~/tools/sfdx/install
        - run:
            name: create tmp dir and server key; check server key
            command: |
                mkdir ~/tools/sfdx-keys 
                echo $SSL_SERVER_KEY_HEX | xxd -r -ps >> ~/tools/sfdx-keys/server.key;
                openssl rsa -in ~/tools/sfdx-keys/server.key -check -noout
        - run:
            name: check auth for dev hub
            command: |
                sfdx force:auth:jwt:grant --clientid $DX_CONSUMER_KEY --jwtkeyfile ~/tools/sfdx-keys/server.key --username $DX_USER --setdefaultdevhubusername --setalias hub
        - run: 
            name: just checking ls againnnn
            command: ls -a
        - save_cache: 
            key: sfdx
            paths: 
                - ~/.sfdx
        - persist_to_workspace:
            root: ~/tools/sfdx-keys
            paths:
                - server.key
        - store_artifacts:
            path: ~/.sfdx/sfdx.log
            destination: sfdx-logs      


    test-cache:
        machine: true 
        steps: 
            - attach_workspace:
                at: ~/tools/
            - restore_cache:
                    keys: 
                        - sfdx
            - run: 
                name: DX Install
                command: ./tools/sfdx/install
            - run: 
                name: does dx work? 
                command: sfdx force:org:list
            - run: 
                name: just checking ls againnnn
                command: ls -a


    finalize:
        machine: true 
        steps:
            - run:
                name: print final success statement => could be used to delete scratch orgs
                command: echo HOOORAY
                when: always



workflows:
  version: 2
  run_build:
    jobs:
      - setup-dx-environment:
          context: org-global
          filters:
            branches:
              only:
                - master
      - test-cache:
          context: org-global
          requires: 
                - setup-dx-environment
      
      
      
      
      
      
      
      
      
      