version: 2
jobs:
    setup-dx-environment:
        machine: true 
        steps:
        - run:
            name: Download DX and store 
            command: |
                mkdir ~/tools
                wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJf - --directory ~/tools/
                ~/tools/sfdx/install
        - run:
            name: create tmp dir and server key; check server key
            command: |
                mkdir ~/tools/sfdx-keys 
                echo $SSL_SERVER_KEY_HEX | xxd -r -ps >> ~/tools/sfdx-keys/server.key;
                openssl rsa -in ~/tools/sfdx-keys/server.key -check -noout
        - run:
            name: check auth for dev hub
            command: |
                sfdx force:auth:jwt:grant --clientid $DX_CONSUMER_KEY --jwtkeyfile ~/tools/sfdx-keys/server.key --username $DX_USER --setdefaultdevhubusername --setalias hub
        - persist_to_workspace:
            root: ~/
            paths:
                - tools/*
                - .sfdx/*
        - store_artifacts:
            path: ~/.sfdx/sfdx.log
            destination: sfdx-logs      


    create-1st-feature-org:
        machine: true 
        steps: 
            - attach_workspace:
                at: ~/
            - run: 
                name: DX Install
                command: ~/tools/sfdx/install
            - run: 
                name: Create feature Org  
                command: sfdx force:org:create \
                            --definitionfile config/project-scratch-def.json \
                            --setalias feature1
            - persist_to_workspace:
                root: ~/
                paths:
                    - tools/*
                    - .sfdx/*

    create-2nd-feature-org:
        machine: true 
        steps: 
            - attach_workspace:
                at: ~/
            - run: 
                name: DX Install
                command: ~/tools/sfdx/install
            - run: 
                name: Create feature Org  
                command: sfdx force:org:create \
                            --definitionfile config/project-scratch-def.json \
                            --setalias feature2
            - persist_to_workspace:
                root: ~/
                paths:
                    - tools/*
                    - .sfdx/*

    test-all:
        machine: true 
        steps: 
            - attach_workspace:
                at: ~/
            - run: 
                name: Check
                command: sfdx force:org:display

workflows:
  version: 2
  run_build:
    jobs:
      - setup-dx-environment:
          context: org-global
      - create-1st-feature-org:
          context: org-global
          requires: 
                - setup-dx-environment
      - create-2nd-feature-org:
            context: org-global
            requires: 
                - setup-dx-environment
      - test-all:
            requires: 
                - setup-dx-environment
      