version: 2
jobs:
    setup-dx-environment:
        machine: true 
        steps:
        - run:
            name: Download DX and store 
            command: |
                mkdir ~/tools
                wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJf - --directory ~/tools/
                ~/tools/sfdx/install
        - run:
            name: create tmp dir and server key; check server key
            command: |
                mkdir ~/tools/sfdx-keys 
                echo $SSL_SERVER_KEY_HEX | xxd -r -ps >> ~/tools/sfdx-keys/server.key;
                openssl rsa -in ~/tools/sfdx-keys/server.key -check -noout
        - run:
            name: check auth for dev hub
            command: |
                sfdx force:auth:jwt:grant --clientid $DX_CONSUMER_KEY --jwtkeyfile ~/tools/sfdx-keys/server.key --username $DX_USER --setdefaultdevhubusername --setalias hub
        - persist_to_workspace:
            root: ~/
            paths:
                - tools/*
                - .sfdx/*
        - store_artifacts:
            path: ~/.sfdx/sfdx.log
            destination: sfdx-logs      


    create-1st-feature-org-and-run-tests:
        machine: true 
        steps: 
            - checkout
            - attach_workspace:
                at: ~/
            - run: 
                name: DX Install
                command: ~/tools/sfdx/install
            - run: 
                name: Create 1st feature Org  
                command: |
                    sfdx force:org:create --definitionfile ./config/project-scratch-def.json \
                            --setalias feature1 \
                            --durationdays 1
                            sfdx force:source:push -u feature1
                            sfdx force:data:soql:query -q "select Name from apexclass where name like '%Test'" -u feature1 --json >> ~/tools/ApexTests.json
                            testsToRun=$(cat ~/tools/ApexTests.json | jq -r '.result.records[0:length/2] | .[] .Name+","' --join-output)
                            echo Tests to run - $testsToRun
                            sfdx force:apex:test:run -n SObjectServiceTest \ 
                                    -u feature1 \
                                    --wait 10 \
            - store_test_results:
                path: ~/test-results
            - store_artifacts:
                path: ~/test-results
                destination: test-results
            - store_artifacts:
                path: ~/.sfdx/sfdx.log
                destination: sfdx-logs
        

    create-2nd-feature-org-and-run-tests:
        machine: true 
        steps: 
            - checkout
            - attach_workspace:
                at: ~/
            - run: 
                name: DX Install
                command: ~/tools/sfdx/install
            - run: 
                name: Create 2nd feature Org and push source
                command: |
                    sfdx force:org:create --definitionfile ./config/project-scratch-def.json \
                            --setalias feature2 \
                            --durationdays 1
                    sfdx force:source:push -u feature2
            - run:
                name: Query Tests 
                command: |
                    sfdx force:data:soql:query -q "select Name from apexclass where name like '%Test'" -u feature2 --json >> ~/tools/ApexTests.json
                    testsToRun=$(cat ~/tools/ApexTests.json | jq -r '.result.records[length/2:length] | .[] .Name+","' --join-output)
                    echo Tests To run - $testsToRun
            - run:  
                name: Run Tests
                command: |        
                    sfdx force:apex:test:run -u feature2 -w 10 -n $testsToRun
            - store_test_results:
                path: ~/test-results
            - store_artifacts:
                path: ~/test-results
                destination: test-results
            - store_artifacts:
                path: ~/.sfdx/sfdx.log
                destination: sfdx-logs

    test-all:
        machine: true 
        steps: 
            - attach_workspace:
                at: ~/
            - run: 
                name: DX Install
                command: ~/tools/sfdx/install
            - run: 
                name: Check
                command: sfdx force:org:display

workflows:
  version: 2
  feature_build:
    jobs:
      - setup-dx-environment
      - create-1st-feature-org-and-run-tests:
          requires: 
                - setup-dx-environment
      - create-2nd-feature-org-and-run-tests:
            requires: 
                - setup-dx-environment
      - test-all:
            requires: 
                - setup-dx-environment
                - create-1st-feature-org-and-run-tests
                - create-2nd-feature-org-and-run-tests
      